import json
import logging
from typing import Optional

import httpx

from app.core.config import settings
from app.utils.helpers import split_into_sentences

logger = logging.getLogger(__name__)

DETECTION_SYSTEM_PROMPT = """You are an AI content detection expert. Analyze the given text and determine the likelihood that each sentence was generated by AI.

For each sentence, provide:
- The sentence text
- A confidence score from 0.0 to 1.0 (0 = definitely human, 1 = definitely AI)
- A label: "human" (score < 0.4), "suspicious" (0.4-0.7), or "ai" (score > 0.7)

Also provide an overall AI probability score from 0 to 100.

Respond ONLY with valid JSON in this exact format:
{
    "ai_score": <number 0-100>,
    "highlights": [
        {"sentence": "<sentence text>", "score": <0.0-1.0>, "label": "<human|suspicious|ai>"}
    ]
}

Analyze patterns like:
- Overly formal or uniform sentence structure
- Lack of personal voice or idiomatic expressions
- Perfect grammar with no natural variation
- Generic or template-like phrasing
- Transitional phrases typical of AI (Moreover, Furthermore, In conclusion)
"""

HUMANIZE_SYSTEM_PROMPT = """You are an expert text rewriter. Your task is to rewrite the given text to sound more naturally human-written while preserving the original meaning and key information.

Tone: {tone}

Guidelines for each tone:
- casual: Use conversational language, contractions, informal expressions, personal anecdotes
- professional: Clear and polished but with natural variation, industry-appropriate vocabulary
- academic: Scholarly but with genuine analytical voice, varied sentence structures, nuanced arguments

Make the text feel authentic by:
- Varying sentence length and structure
- Adding natural transitions
- Using active voice where natural
- Including subtle imperfections that real humans make
- Avoiding AI-typical phrases like "It's important to note", "Furthermore", "In conclusion"

Return ONLY the rewritten text, no explanations or metadata."""


async def detect_ai_content(text: str) -> dict:
    """
    Analyze text for AI-generated content using OpenAI API.
    Returns structured detection results.
    """
    if not settings.OPENAI_API_KEY or settings.OPENAI_API_KEY.startswith("sk-your"):
        # Fallback mock response for development without API key
        return _mock_detection(text)

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {settings.OPENAI_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": "gpt-4o-mini",
                    "messages": [
                        {"role": "system", "content": DETECTION_SYSTEM_PROMPT},
                        {"role": "user", "content": text},
                    ],
                    "temperature": 0.1,
                    "response_format": {"type": "json_object"},
                },
            )

            if response.status_code != 200:
                logger.error(f"OpenAI API error: {response.status_code} - {response.text}")
                return _mock_detection(text)

            data = response.json()
            content = data["choices"][0]["message"]["content"]
            result = json.loads(content)

            # Validate and normalize
            result["ai_score"] = max(0, min(100, float(result.get("ai_score", 50))))
            for h in result.get("highlights", []):
                h["score"] = max(0.0, min(1.0, float(h.get("score", 0.5))))
                if h["score"] >= 0.7:
                    h["label"] = "ai"
                elif h["score"] >= 0.4:
                    h["label"] = "suspicious"
                else:
                    h["label"] = "human"

            return result

    except Exception as e:
        logger.error(f"AI detection error: {e}")
        return _mock_detection(text)


async def humanize_text(text: str, tone: str = "professional") -> str:
    """
    Rewrite text to sound more human-like using OpenAI API.
    Returns the rewritten text.
    """
    if not settings.OPENAI_API_KEY or settings.OPENAI_API_KEY.startswith("sk-your"):
        return _mock_humanize(text, tone)

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {settings.OPENAI_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": "gpt-4o-mini",
                    "messages": [
                        {
                            "role": "system",
                            "content": HUMANIZE_SYSTEM_PROMPT.format(tone=tone),
                        },
                        {"role": "user", "content": text},
                    ],
                    "temperature": 0.8,
                },
            )

            if response.status_code != 200:
                logger.error(f"OpenAI API error: {response.status_code} - {response.text}")
                return _mock_humanize(text, tone)

            data = response.json()
            return data["choices"][0]["message"]["content"].strip()

    except Exception as e:
        logger.error(f"Humanize error: {e}")
        return _mock_humanize(text, tone)


def _mock_detection(text: str) -> dict:
    """Mock detection for development without API key."""
    import random
    sentences = split_into_sentences(text)
    highlights = []
    total_score = 0

    for sentence in sentences:
        # Generate semi-realistic scores based on sentence characteristics
        score = random.uniform(0.2, 0.9)

        # Adjust based on heuristics
        if len(sentence.split()) > 20:
            score += 0.1
        if any(word in sentence.lower() for word in
               ["furthermore", "moreover", "in conclusion", "it is important"]):
            score += 0.2
        if sentence.startswith(("I ", "My ", "We ")):
            score -= 0.2

        score = max(0.0, min(1.0, score))
        total_score += score

        if score >= 0.7:
            label = "ai"
        elif score >= 0.4:
            label = "suspicious"
        else:
            label = "human"

        highlights.append({
            "sentence": sentence,
            "score": round(score, 2),
            "label": label,
        })

    avg_score = (total_score / len(sentences)) * 100 if sentences else 50

    return {
        "ai_score": round(min(100, max(0, avg_score)), 1),
        "highlights": highlights,
    }


def _mock_humanize(text: str, tone: str) -> str:
    """Mock humanization for development without API key."""
    prefix_map = {
        "casual": "Hey, so here's the thing — ",
        "professional": "Based on our analysis, ",
        "academic": "Upon careful examination, ",
    }
    prefix = prefix_map.get(tone, "")
    # Simple mock: just return the text with a prefix to show it changed
    return f"{prefix}{text}"
